### ISSUE TITLE
A better way to get rid of a.out files.

### ISSUE THREAD

**Issue by sahilrajput03** [dhanur350/TDM_CPP-17#1]
> Please ignore the a.out file as I do code in linux and G++ compiler produces a.out file everytime when my code gets compiled successfully.

You can add a `.gitignore` file in the root folder of your repository with contents:

```
a.out
```

and that'll ignore the `a.out` files from anywhere.

**Comment by sahilrajput03** [comment]
Please close the issue yourself when you do this fix!

**Comment by dhanur350** [comment]
That's a great idea , and it's worked , thank you for this tip idea. 
## `classic`
